baseURL = 'https://KMINGON.github.io/'
languageCode = 'ko-kr'
title = '보안 연구 노트'

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false


[params]
title = "RTCat's Lab"   # 사이드바 타이틀(사이트 title과 별개)
author = "RTCat"
description = "보안 학습 과정에서 얻은 인사이트 저장소"
profilePicture = "images/4.png"
mainSections = ["note", "analysis", "review"]  # 홈에 2개 섹션 글 모두 노출, 이후 project 섹션 추가 예정
readMore = true # 가볍게 요약 정렬


[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/KMINGON"


[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Note"
    identifier = "note"
    url = "/note/"
    weight = 20

  [[menu.main]]
    name = "Analysis"
    identifier = "analysis"
    url = "/analysis/"
    weight = 30

  [[menu.main]]
    name = "Review"
    identifier = "review"
    url = "/review/"
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"